CODE-for-GIFU/covid19

assets/locales/en.json
- close #38 
- 岐阜県公式ではないので修正
- <li>タグが出てしまっていたので修正
=> fix english statement

nuxt.config.js
- close #42 
- GoogleアナリティクスのトラッキングIDを新規作成、組み込み
※エディタの整形機能が働いたため、コード変更箇所がありますが、実際はIDのみ
=> add Google Analytics

README.md, layouts/default.vue, pages/about.vue
- close #24 
- #57 
- CODE-for-GIFUに変更
- /layouts/default.vueの東京版のURLを変更
=> 当サイトについてのgithubのリンクを修正しました

api/sheet.js, pages/index.vue
- close #68
- グラフに使用するデータを外部から読み込むようにした
- 使用していない処理を削除した
=> 外部のJSONファイルを読み込むようにした

components/TimeBarChart.vue, pages/index.vue
- close #82 
* 暫定対応で、注意書きを追記。後ほど、3/24データに3/11からの差分を追記する。
=> 検査実査数の注意書きを追記

components/DataTable.vue, components/TimeBarChart.vue, pages/index.vue
- close #79
- データ読み込みが終わるまでデータ表示部分にローディングを表示
=> データ読み込み中にローディングを表示

assets/variables.scss
=> リンクの文字の色を修正

api/sheet.js, pages/index.vue
- グラフ用データの取得先URLを変更
- 日付の書式を明確にした
=> スプレッドシート変更に伴う修正

api/sheet.js, components/WhatsNew.vue
- close #105 
- お知らせの表示件数を変更
- 文字の大きさと間隔を修正
=> お知らせを最新2件のみ表示するようにした

components/ConfirmedCasesTable.vue
- close #112 
- 表示崩れを起こさないように修正
=> 検査実施数の表示崩れに対応

pages/municipalities.vue
=> build error に対応

components/VideoPlayer.vue, package.json, pages/precaution.vue, yarn.lock
- close #116 
- 対策ページに YouTube 表示
- レスポンシブ対応
https://rnsk-dev-covid19.netlify.com/precaution/
=> 岐阜県公式の YouTube 動画を表示

components/TimeBarChart.vue, pages/index.vue
- close #139 
- グラフ内の文字列を多言語対応
https://rnsk-dev-covid19.netlify.com/
=> グラフ内で多言語化されていない箇所を修正

api/sheet.js
- #16 
- sheet.jsに相談窓口一覧データの取得を追加
- 表示部分については作成中
- マッピングする部分については保留
=> 相談窓口一覧のデータ取得部分を追加

api/sheet.js
=> サンプルデータから陽性患者数のグラフを生成

api/sheet.js, utils/formatTable.ts
- #170
- いただいたデモデータにある No を表示しました。
=> 陽性患者の属性の表にNoを表示

api/sheet.js
=> データリンク先を変更

api/sheet.js
- close #175 
- スプレッドシート参照先を1つのシートにまとめたので参照先を変更
=> スプレッドシート参照先の変更

components/flow/FlowPc.vue, components/flow/FlowPcPcr.vue, components/flow/FlowPcSuspect.vue, components/flow/FlowSpAccording.vue, components/flow/FlowSpSuspect.vue, pages/precaution.vue
- close #186
- close #187 
- 動画のリンク切れを修正(今後の修正も見込んで一旦コメントアウトにします)
- 東京都の記載残りを修正
=> 東京都の記載残りを削除、動画リンクの修正

api/sheet.js
- #185 
- オープンデータ運用変更に備えてスプレッドシートを変更
(相談窓口や自治体一覧など、複数使用していたスプレッドシートを一元化しました)
=> 新しいスプレッドシートに運用変更

components/TimeBarChart.vue
- close #204
- 注釈が翻訳されるように処理を修正
　※翻訳動作確認時には下記コードを付与していましたが、その他の検証の際に間違って外していました
=> TimeBarChartの注釈が翻訳されるように修正

components/SideNavigation.vue
- close #215 
- z-index の変更
https://rnsk-dev-covid19.netlify.app/
=> #215 重なりの順序を数値で指定

api/sheet.js
- close #230
- スプレッドシートの読み込み先を変更
https://rnsk-dev-covid19.netlify.app/
=> スプレッドシートの読み込み先を変更とそれに伴うデータ加工処理の変更

components/SideNavigation.vue, pages/index.vue
=> トップページのリンク修正

pages/flow2.vue
=> フローの文言修正漏れの対応

pages/flow2.vue, pages/index.vue
- close #{ISSUE_NUMBER}
- xxxxxx
- xxx
=> merge development 11/1

components/SideNavigation.vue
=> #234 サイドナビゲーションの古いURLを修正

api/sheet.js, pages/index.vue
- close #270 
- オープンデータカタログサイトのcsvデータ内のLast-Modifiedヘッダーより情報を取得したデータを反映。
※トップの最新日時と、サマリーの最新日時が同じものを参照していたため、それも別のものを参照するように変更。
=> オープンデータカタログサイトの最新データ更新日付表示に対応
